### ISSUE TITLE
docs: wrong location for apache config files

### ISSUE THREAD

**Issue by bua-dns** [bua-dns/multi-directus-generator#1]
Dear Viktor,

In the documentation, examples 1 and 2, the location of the apache config file is given as:

Apache-Virtualhost-Config Datei: /etc/apache2/subone.domain.tld.conf

but should be:

Apache-Virtualhost-Config Datei: /etc/apache2/sites-available/subone.domain.tld.conf

Best, Michael

**Comment by grandgeorg** [comment]
Fixed in 82527d4844150a9c5253f8be72599df345ba2518
